[workspace]
resolver = "2"
members = [
    "portcullis-toml",
    "portcullis-jail",
    "portcullis-policy",
    "portcullis-ipc",
    "portcullis-protocol",
    "portcullis-cli",
    "portcullisd",
    "atrium-session",
    "jaild-policy",
    "jaild",
    "portcullis-sig",
    "portcullis-peer",
    "atrium-volumes",
    "ostiarius",
]

[workspace.package]
version      = "0.1.0"
edition      = "2021"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/atrium-os/atrium"
rust-version = "1.75"

[profile.release]
lto           = "thin"
codegen-units = 1
opt-level     = 3
