#!/bin/sh
# atrium-vk-icd loader smoke test (macOS host)
#
# Drives atrium-vk-icd through the Khronos Vulkan loader on the
# macOS host, the way a real Vulkan app would.  Validates the
# entire ICD ABI surface (negotiate / GetInstanceProcAddr / dispatch)
# end-to-end, including the aqueduct-gpu-host handshake.
#
# Three rungs:
#
#   1. ABI rung    -- no daemon.  Loader loads our dylib, calls
#                     vkCreateInstance + vkEnumeratePhysicalDevices.
#                     We expect 0 devices and the loader's synthesized
#                     VK_ERROR_INITIALIZATION_FAILED.  Confirms the
#                     ICD entry-point surface is wired correctly.
#
#   2. Daemon rung -- with aqueduct-gpu-host (--backend software).
#                     vkEnumeratePhysicalDevices returns 1 device
#                     reported as "atrium-vk-icd (software:0)".
#                     Confirms the wire-protocol handshake works
#                     through the loader.
#
#   3. vulkaninfo  -- full vulkaninfo readout against the daemon
#                     run.  Exercises GetPhysicalDeviceFeatures /
#                     Properties / FormatProperties / QueueFamily
#                     Properties through to completion.
#
# Pre-reqs (one-time):
#   * brew install vulkan-headers vulkan-loader vulkan-tools
#   * cargo build -p atrium-vk-icd          (produces .dylib)
#   * cargo build -p aqueduct-gpu-host      (produces daemon)
#
# Usage:
#   ./scripts/loader_smoke_macos.sh

set -eu

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DYLIB="$REPO_ROOT/atrium-vk-icd/target/debug/libatrium_vk_icd.dylib"
DAEMON="$REPO_ROOT/aqueduct-gpu-host/target/debug/aqueduct-gpu-host"
SOCKET="/tmp/atrium-vk-icd-loader-smoke.sock"
MANIFEST="$(mktemp -t atrium_icd.XXXXXX).json"

if [ ! -f "$DYLIB" ]; then
    echo "missing $DYLIB -- cargo build -p atrium-vk-icd first" >&2
    exit 1
fi
if [ ! -x "$DAEMON" ]; then
    echo "missing $DAEMON -- cargo build -p aqueduct-gpu-host first" >&2
    exit 1
fi
if ! command -v vulkaninfo >/dev/null 2>&1; then
    echo "missing vulkaninfo -- brew install vulkan-tools" >&2
    exit 1
fi
if [ ! -f "/opt/homebrew/lib/libvulkan.dylib" ]; then
    echo "missing /opt/homebrew/lib/libvulkan.dylib -- brew install vulkan-loader" >&2
    exit 1
fi

cat > "$MANIFEST" <<EOF
{
    "_comment": "atrium-vk-icd loader smoke-test manifest (generated by scripts/loader_smoke_macos.sh).",
    "file_format_version": "1.0.1",
    "ICD": {
        "library_path": "$DYLIB",
        "api_version": "1.3.0"
    }
}
EOF
echo "==> manifest: $MANIFEST"

cleanup() {
    if [ -n "${DAEMON_PID:-}" ]; then
        kill "$DAEMON_PID" 2>/dev/null || true
        wait 2>/dev/null || true
    fi
    rm -f "$SOCKET" "$MANIFEST"
}
trap cleanup EXIT INT TERM

# ── Rung 1: ABI smoke (no daemon) ────────────────────────────────
echo
echo "=== Rung 1: no daemon -- expect VK_ERROR_INITIALIZATION_FAILED ==="
set +e
DYLD_LIBRARY_PATH=/opt/homebrew/lib \
  VK_DRIVER_FILES="$MANIFEST" \
  vulkaninfo --summary 2>&1 | tail -5
set -e

# ── Rung 2 + 3: with daemon ──────────────────────────────────────
rm -f "$SOCKET"
"$DAEMON" --socket "$SOCKET" --backend software >/tmp/aqueduct-loader-smoke.log 2>&1 &
DAEMON_PID=$!
sleep 1
if ! kill -0 "$DAEMON_PID" 2>/dev/null; then
    echo "daemon failed to start; log:" >&2
    cat /tmp/aqueduct-loader-smoke.log >&2
    exit 1
fi
echo
echo "=== Rung 2: daemon up -- expect 1 device ==="
DYLD_LIBRARY_PATH=/opt/homebrew/lib \
  VK_DRIVER_FILES="$MANIFEST" \
  ATRIUM_VK_ICD_SOCKET="$SOCKET" \
  vulkaninfo --summary 2>&1 | grep -E "Devices:|GPU0:|apiVersion|deviceName|deviceType" | head -10

echo
echo "=== Rung 3: full vulkaninfo readout exit code ==="
DYLD_LIBRARY_PATH=/opt/homebrew/lib \
  VK_DRIVER_FILES="$MANIFEST" \
  ATRIUM_VK_ICD_SOCKET="$SOCKET" \
  vulkaninfo > /tmp/atrium-vulkaninfo.out 2>&1
echo "vulkaninfo exit=$?  (output in /tmp/atrium-vulkaninfo.out, $(wc -l </tmp/atrium-vulkaninfo.out | tr -d ' ') lines)"

echo
echo "OK: loader smoke clean through all 3 rungs."
