/*
 * fresco.ko — FreeBSD newbus driver for the Fresco GPU transport.
 *
 * Attaches to the ivshmem-doorbell PCI device (vendor 0x1af4, device
 * 0x1110) exposed by our modified QEMU. Exposes /dev/fresco0 with:
 *   - mmap of BAR2 (16 MiB shmem) for the command/completion/input
 *     rings + CAS staging area
 *   - kqueue EVFILT_READ that wakes when the host advances the
 *     completion or input ring's write pointer. Implemented via a
 *     1 ms kernel callout (NOT MSI-X) — see "polling" note below.
 *   - ioctls for ringing the doorbell back at the host and reading
 *     diagnostic counters
 *
 * Why polling, not MSI-X:
 *   FreeBSD on qemu's `virt` machine under HVF cannot allocate MSI-X
 *   for late-attaching PCI devices. The IORT generated by qemu for
 *   gic-version=2 is empty, and forcing FDT mode (acpi=off) breaks
 *   boot (no event timer). Disabling ACPI is a non-starter, and
 *   patching qemu/FreeBSD's IORT generation is out of scope.
 *   ivshmem-doorbell only delivers via MSI-X, so we sidestep the
 *   doorbell entirely: we mirror the host's "1 ms poll timer"
 *   workaround on the guest side. Cost is ~0.1% CPU at idle.
 *
 * No DRM, no linuxkpi, no GPU-vendor abstraction. The transport is
 * generic shmem; the GPU API lives entirely in userspace, defined by
 * the Fresco wire protocol (reference server implementation lives at
 * ~/src/karythra-gpu-server, originally named for its first consumer).
 */

#include <sys/param.h>
#include <sys/systm.h>
#include <sys/kernel.h>
#include <sys/module.h>
#include <sys/bus.h>
#include <sys/conf.h>
#include <sys/malloc.h>
#include <sys/lock.h>
#include <sys/mutex.h>
#include <sys/rman.h>
#include <sys/uio.h>
#include <sys/selinfo.h>
#include <sys/event.h>
#include <sys/proc.h>

#include <machine/bus.h>
#include <machine/resource.h>

#include <vm/vm.h>
#include <vm/pmap.h>

#include <dev/pci/pcireg.h>
#include <dev/pci/pcivar.h>

#include "fresco_ioctl.h"

#define FRESCO_PCI_VENDOR     0x1af4
#define FRESCO_PCI_DEVICE     0x1110  /* ivshmem-doorbell */

/* BAR0 register offsets (ivshmem device regs). */
#define IVSHMEM_REG_INTRMASK    0x00
#define IVSHMEM_REG_INTRSTATUS  0x04
#define IVSHMEM_REG_IVPOSITION  0x08
#define IVSHMEM_REG_DOORBELL    0x0c

#define FRESCO_PEER_SERVER    0       /* server is always peer 0 */

/* Shmem control register offsets (must match the server's
 * src/platform/ivshmem.rs in the reference implementation). */
/* (Old single-ring comp regs at 0x08/0x0c retired — comp rings are
 * per-slot; see FRESCO_CTRL_SLOT_COMP_* macros below.) */
/* Multi-client layout (mirrors fresco-server/src/platform/ivshmem.rs). */
#define FRESCO_NUM_CLIENT_SLOTS   4

#define FRESCO_CTRL_SLOTS_ALIVE_MASK 0x40

/* Per-slot control registers: slot i lives at 0x100 + 24*i.
 *   +0  cmd_write    +4  cmd_read
 *   +8  comp_write  +12  comp_read
 *  +16  input_write +20  input_read
 */
#define FRESCO_CTRL_PER_SLOT_BASE 0x100
/* 32-byte stride: 24 bytes used today (cmd/comp/input R/W), 8 bytes
 * reserved for future per-slot state. Must match the server and
 * libfresco. */
#define FRESCO_CTRL_PER_SLOT_STRIDE 32
#define FRESCO_CTRL_SLOT_COMP_WRITE(s) \
        (FRESCO_CTRL_PER_SLOT_BASE + (s) * FRESCO_CTRL_PER_SLOT_STRIDE + 8)
#define FRESCO_CTRL_SLOT_COMP_READ(s) \
        (FRESCO_CTRL_PER_SLOT_BASE + (s) * FRESCO_CTRL_PER_SLOT_STRIDE + 12)
#define FRESCO_CTRL_SLOT_INPUT_WRITE(s) \
        (FRESCO_CTRL_PER_SLOT_BASE + (s) * FRESCO_CTRL_PER_SLOT_STRIDE + 16)
#define FRESCO_CTRL_SLOT_INPUT_READ(s) \
        (FRESCO_CTRL_PER_SLOT_BASE + (s) * FRESCO_CTRL_PER_SLOT_STRIDE + 20)

/* Poll period for completion/input ring head pointer. 1 ms ≈ 0.1% CPU. */
#define FRESCO_POLL_HZ            1000

struct fresco_softc {
        device_t                dev;
        struct cdev            *cdev;

        /* PCI BARs */
        struct resource        *regs_res;     /* BAR0: device registers */
        int                     regs_rid;
        struct resource        *msix_res;     /* BAR1: MSI-X table */
        int                     msix_rid;
        struct resource        *shmem_res;    /* BAR2: 16 MiB shared memory */
        int                     shmem_rid;
        bus_size_t              shmem_size;

        /* Polling state. */
        struct callout          poll_co;

        /* Slot allocator: bit i set ⇒ slot i in use. Updated under
         * mtx on open/close. The same mutex covers wake-count and
         * KNOTE state, so all per-instance bookkeeping is one lock. */
        uint16_t                slot_in_use;

        struct mtx              mtx;
        struct selinfo          sel;
        struct knlist           knl;
        uint64_t                wake_count;
};

static d_open_t          fresco_open;
static d_close_t         fresco_close;
static d_ioctl_t         fresco_ioctl;
static d_mmap_t          fresco_mmap;
static d_kqfilter_t      fresco_kqfilter;

static struct cdevsw fresco_cdevsw = {
        .d_version = D_VERSION,
        .d_name    = "fresco",
        .d_open    = fresco_open,
        .d_close   = fresco_close,
        .d_ioctl   = fresco_ioctl,
        .d_mmap    = fresco_mmap,
        .d_kqfilter = fresco_kqfilter,
};

/* ------------------------------------------------------------------ */
/* Polling — replaces MSI-X interrupt path                             */
/* ------------------------------------------------------------------ */

static uint32_t
fresco_shmem_read_u32(struct fresco_softc *sc, bus_size_t off)
{
        return (bus_read_4(sc->shmem_res, off));
}

static void
fresco_shmem_write_u32(struct fresco_softc *sc, bus_size_t off, uint32_t val)
{
        bus_write_4(sc->shmem_res, off, val);
}

/* Atomically OR/AND the live-slots bitmask. Caller holds sc->mtx,
 * which serializes all slot bookkeeping — no other writer races us. */
static void
fresco_alive_set(struct fresco_softc *sc, int slot)
{
        uint32_t m = fresco_shmem_read_u32(sc, FRESCO_CTRL_SLOTS_ALIVE_MASK);
        fresco_shmem_write_u32(sc, FRESCO_CTRL_SLOTS_ALIVE_MASK,
            m | (1u << slot));
}

static void
fresco_alive_clear(struct fresco_softc *sc, int slot)
{
        uint32_t m = fresco_shmem_read_u32(sc, FRESCO_CTRL_SLOTS_ALIVE_MASK);
        fresco_shmem_write_u32(sc, FRESCO_CTRL_SLOTS_ALIVE_MASK,
            m & ~(uint32_t)(1u << slot));
}

static void
fresco_poll_cb(void *arg)
{
        struct fresco_softc *sc = arg;
        int slot, pending = 0;

        /* Callout was initialized with callout_init_mtx; sc->mtx is
         * already held on entry. */
        mtx_assert(&sc->mtx, MA_OWNED);

        /* KNOTE while there is *pending unread data* on ANY per-slot
         * completion or input ring. The pending-not-edge variant
         * fixes a register-after-poll race where a one-shot edge wake
         * would be missed. Cost: a handful of MMIO reads per ms. */
        for (slot = 0; !pending && slot < FRESCO_NUM_CLIENT_SLOTS; slot++) {
                uint32_t cw = fresco_shmem_read_u32(sc,
                    FRESCO_CTRL_SLOT_COMP_WRITE(slot));
                uint32_t cr = fresco_shmem_read_u32(sc,
                    FRESCO_CTRL_SLOT_COMP_READ(slot));
                uint32_t iw = fresco_shmem_read_u32(sc,
                    FRESCO_CTRL_SLOT_INPUT_WRITE(slot));
                uint32_t ir = fresco_shmem_read_u32(sc,
                    FRESCO_CTRL_SLOT_INPUT_READ(slot));
                if (cw != cr || iw != ir)
                        pending = 1;
        }

        if (pending) {
                sc->wake_count++;
                KNOTE_LOCKED(&sc->knl, 0);
                selwakeuppri(&sc->sel, PRIBIO);
        }
        callout_schedule(&sc->poll_co, hz / FRESCO_POLL_HZ);
}

/* ------------------------------------------------------------------ */
/* kqueue                                                              */
/* ------------------------------------------------------------------ */

static void
fresco_kq_detach(struct knote *kn)
{
        struct fresco_softc *sc = kn->kn_hook;
        knlist_remove(&sc->knl, kn, 0);
}

static int
fresco_kq_event(struct knote *kn, long hint)
{
        struct fresco_softc *sc = kn->kn_hook;
        kn->kn_data = sc->wake_count;
        return (1);
}

static struct filterops fresco_read_filterops = {
        .f_isfd   = 1,
        .f_detach = fresco_kq_detach,
        .f_event  = fresco_kq_event,
};

static int
fresco_kqfilter(struct cdev *cdev, struct knote *kn)
{
        struct fresco_softc *sc = cdev->si_drv1;

        if (kn->kn_filter != EVFILT_READ)
                return (EINVAL);

        kn->kn_fop  = &fresco_read_filterops;
        kn->kn_hook = sc;
        knlist_add(&sc->knl, kn, 0);
        return (0);
}

/* ------------------------------------------------------------------ */
/* cdev ops                                                            */
/* ------------------------------------------------------------------ */

/*
 * Per-open state. Pointer attached to the file via devfs_set_cdevpriv;
 * the dtor releases the slot on the last close (or when the
 * descriptor is force-closed by the kernel).
 */
struct fresco_open_state {
        struct fresco_softc    *sc;
        int                     slot;        /* 0..FRESCO_NUM_CLIENT_SLOTS-1 */
};

static void
fresco_open_dtor(void *arg)
{
        struct fresco_open_state *st = arg;
        if (st == NULL)
                return;
        mtx_lock(&st->sc->mtx);
        st->sc->slot_in_use &= ~(uint16_t)(1u << st->slot);
        fresco_alive_clear(st->sc, st->slot);
        mtx_unlock(&st->sc->mtx);
        /* Ring the doorbell so the server wakes and notices the
         * disconnect immediately. Without this, the server only
         * polls the alive mask when something else triggers a
         * redraw (cursor move, surviving client's command). */
        uint32_t db = ((uint32_t)FRESCO_PEER_SERVER << 16) | 0;
        bus_write_4(st->sc->regs_res, IVSHMEM_REG_DOORBELL, db);
        free(st, M_DEVBUF);
}

static int
fresco_open(struct cdev *cdev, int oflags, int devtype, struct thread *td)
{
        struct fresco_softc *sc = cdev->si_drv1;
        struct fresco_open_state *st;
        int slot, error;

        mtx_lock(&sc->mtx);
        for (slot = 0; slot < FRESCO_NUM_CLIENT_SLOTS; slot++) {
                if ((sc->slot_in_use & (1u << slot)) == 0) {
                        sc->slot_in_use |= (1u << slot);
                        fresco_alive_set(sc, slot);
                        break;
                }
        }
        mtx_unlock(&sc->mtx);
        if (slot == FRESCO_NUM_CLIENT_SLOTS)
                return (ENOSPC);

        st = malloc(sizeof(*st), M_DEVBUF, M_WAITOK | M_ZERO);
        st->sc = sc;
        st->slot = slot;

        error = devfs_set_cdevpriv(st, fresco_open_dtor);
        if (error != 0) {
                mtx_lock(&sc->mtx);
                sc->slot_in_use &= ~(uint16_t)(1u << slot);
                fresco_alive_clear(sc, slot);
                mtx_unlock(&sc->mtx);
                free(st, M_DEVBUF);
                return (error);
        }
        return (0);
}

static int
fresco_close(struct cdev *cdev, int fflag, int devtype, struct thread *td)
{
        /* Slot release happens in fresco_open_dtor on cdevpriv free. */
        return (0);
}

static int
fresco_ioctl(struct cdev *cdev, u_long cmd, caddr_t data, int fflag,
    struct thread *td)
{
        struct fresco_softc *sc = cdev->si_drv1;

        switch (cmd) {
        case FRESCO_IOC_DOORBELL: {
                uint16_t vector = *(uint16_t *)data;
                uint32_t val = ((uint32_t)FRESCO_PEER_SERVER << 16) | vector;
                bus_write_4(sc->regs_res, IVSHMEM_REG_DOORBELL, val);
                return (0);
        }
        case FRESCO_IOC_IVPOSITION: {
                *(uint32_t *)data =
                    bus_read_4(sc->regs_res, IVSHMEM_REG_IVPOSITION);
                return (0);
        }
        case FRESCO_IOC_WAKE_COUNT: {
                mtx_lock(&sc->mtx);
                *(uint64_t *)data = sc->wake_count;
                mtx_unlock(&sc->mtx);
                return (0);
        }
        case FRESCO_IOC_CLIENT_ID: {
                struct fresco_open_state *st;
                int err = devfs_get_cdevpriv((void **)&st);
                if (err != 0 || st == NULL)
                        return (err == 0 ? EBADF : err);
                *(uint32_t *)data = (uint32_t)st->slot;
                return (0);
        }
        }
        return (ENOTTY);
}

static int
fresco_mmap(struct cdev *cdev, vm_ooffset_t offset, vm_paddr_t *paddr,
    int nprot, vm_memattr_t *memattr)
{
        struct fresco_softc *sc = cdev->si_drv1;

        if (offset >= sc->shmem_size)
                return (EINVAL);

        *paddr = rman_get_start(sc->shmem_res) + offset;
        *memattr = VM_MEMATTR_DEFAULT;
        return (0);
}

/* ------------------------------------------------------------------ */
/* Resource setup                                                      */
/* ------------------------------------------------------------------ */

static int
fresco_alloc_resources(struct fresco_softc *sc)
{
        device_t dev = sc->dev;

        sc->regs_rid = PCIR_BAR(0);
        sc->regs_res = bus_alloc_resource_any(dev, SYS_RES_MEMORY,
            &sc->regs_rid, RF_ACTIVE);
        if (sc->regs_res == NULL) {
                device_printf(dev, "could not map BAR0 (regs)\n");
                return (ENXIO);
        }

        /*
         * BAR1 holds the MSI-X table. pci_alloc_msix() requires it to
         * be RF_ACTIVE — without this, alloc returns ENXIO.
         */
        sc->msix_rid = PCIR_BAR(1);
        sc->msix_res = bus_alloc_resource_any(dev, SYS_RES_MEMORY,
            &sc->msix_rid, RF_ACTIVE);
        if (sc->msix_res == NULL) {
                device_printf(dev, "could not map BAR1 (MSI-X table)\n");
                return (ENXIO);
        }

        sc->shmem_rid = PCIR_BAR(2);
        sc->shmem_res = bus_alloc_resource_any(dev, SYS_RES_MEMORY,
            &sc->shmem_rid, RF_ACTIVE);
        if (sc->shmem_res == NULL) {
                device_printf(dev, "could not map BAR2 (shmem)\n");
                return (ENXIO);
        }
        sc->shmem_size = rman_get_size(sc->shmem_res);
        device_printf(dev, "BAR0 regs at %#jx, BAR1 msix at %#jx, BAR2 shmem at %#jx (%ju MiB)\n",
            (uintmax_t)rman_get_start(sc->regs_res),
            (uintmax_t)rman_get_start(sc->msix_res),
            (uintmax_t)rman_get_start(sc->shmem_res),
            (uintmax_t)(sc->shmem_size / (1024 * 1024)));

        return (0);
}

/* MSI-X removed — see header comment. Kept here as a stub in case a future
 * FreeBSD/qemu combination delivers MSI-X correctly and we want to use it. */

/* ------------------------------------------------------------------ */
/* newbus probe / attach / detach                                      */
/* ------------------------------------------------------------------ */

static int
fresco_probe(device_t dev)
{
        if (pci_get_vendor(dev) == FRESCO_PCI_VENDOR &&
            pci_get_device(dev) == FRESCO_PCI_DEVICE) {
                device_set_desc(dev, "Fresco GPU transport (ivshmem-doorbell)");
                return (BUS_PROBE_DEFAULT);
        }
        return (ENXIO);
}

static int
fresco_attach(device_t dev)
{
        struct fresco_softc *sc = device_get_softc(dev);
        int error;

        sc->dev = dev;
        mtx_init(&sc->mtx, "fresco", NULL, MTX_DEF);
        knlist_init_mtx(&sc->knl, &sc->mtx);
        callout_init_mtx(&sc->poll_co, &sc->mtx, 0);

        pci_enable_busmaster(dev);

        error = fresco_alloc_resources(sc);
        if (error != 0)
                goto fail;

        /* Unmask interrupts on the device for completeness — we don't use
         * them, but a future MSI-X path would. */
        bus_write_4(sc->regs_res, IVSHMEM_REG_INTRMASK, 0xffffffff);

        callout_reset(&sc->poll_co, hz / FRESCO_POLL_HZ,
            fresco_poll_cb, sc);

        sc->cdev = make_dev(&fresco_cdevsw, device_get_unit(dev),
            UID_ROOT, GID_WHEEL, 0660, "fresco%d", device_get_unit(dev));
        if (sc->cdev == NULL) {
                error = ENOMEM;
                goto fail;
        }
        sc->cdev->si_drv1 = sc;

        device_printf(dev, "attached: /dev/fresco%d, peer-id=%u\n",
            device_get_unit(dev),
            bus_read_4(sc->regs_res, IVSHMEM_REG_IVPOSITION));
        return (0);

fail:
        return (error);
}

static int
fresco_detach(device_t dev)
{
        struct fresco_softc *sc = device_get_softc(dev);

        if (sc->cdev != NULL)
                destroy_dev(sc->cdev);

        callout_drain(&sc->poll_co);

        if (sc->shmem_res != NULL)
                bus_release_resource(dev, SYS_RES_MEMORY,
                    sc->shmem_rid, sc->shmem_res);
        if (sc->msix_res != NULL)
                bus_release_resource(dev, SYS_RES_MEMORY,
                    sc->msix_rid, sc->msix_res);
        if (sc->regs_res != NULL)
                bus_release_resource(dev, SYS_RES_MEMORY,
                    sc->regs_rid, sc->regs_res);

        knlist_clear(&sc->knl, 0);
        knlist_destroy(&sc->knl);
        seldrain(&sc->sel);
        mtx_destroy(&sc->mtx);
        return (0);
}

/* ------------------------------------------------------------------ */
/* Module glue                                                         */
/* ------------------------------------------------------------------ */

static device_method_t fresco_methods[] = {
        DEVMETHOD(device_probe,  fresco_probe),
        DEVMETHOD(device_attach, fresco_attach),
        DEVMETHOD(device_detach, fresco_detach),
        DEVMETHOD_END
};

static driver_t fresco_driver = {
        "fresco",
        fresco_methods,
        sizeof(struct fresco_softc),
};

DRIVER_MODULE(fresco, pci, fresco_driver, 0, 0);
MODULE_DEPEND(fresco, pci, 1, 1, 1);
MODULE_VERSION(fresco, 1);
