//! `insula init <dir> [--name <app-id>]` — scaffold a
//! new Insula app skeleton.
//!
//! Produces a minimal but valid bundle layout that
//! parses cleanly under `insula info <dir>` and is
//! installable (with `--allow-unsigned`):
//!
//!   <dir>/
//!     manifest.toml      # filled out with sensible defaults
//!     bin/               # ready for the entry binary
//!     .gitignore         # excludes target/ and signature
//!
//! The `[bundle].entry` defaults to `bin/<basename>`
//! using the last path component as the default
//! binary name. Override with `--entry`.

use std::path::{Path, PathBuf};

pub fn cmd_init(args: &[String]) -> Result<(), String> {
    let mut dir: Option<&str> = None;
    let mut app_id: Option<&str> = None;
    let mut entry: Option<&str> = None;
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--name" => {
                app_id = args.get(i + 1).map(|s| s.as_str());
                i += 2;
            }
            "--entry" => {
                entry = args.get(i + 1).map(|s| s.as_str());
                i += 2;
            }
            other if !other.starts_with("--") => {
                if dir.is_some() {
                    return Err(format!(
                        "init: unexpected extra argument {:?}", other
                    ));
                }
                dir = Some(other);
                i += 1;
            }
            other => return Err(format!("init: unknown flag {:?}", other)),
        }
    }
    let dir = dir.ok_or_else(|| "init: missing <dir> argument".to_string())?;
    let dir_path = PathBuf::from(dir);

    if dir_path.exists() {
        let is_empty = dir_path.read_dir()
            .map(|mut it| it.next().is_none())
            .unwrap_or(false);
        if !is_empty {
            return Err(format!(
                "init: {} already exists and is not empty",
                dir_path.display()
            ));
        }
    }
    std::fs::create_dir_all(dir_path.join("bin"))
        .map_err(|e| format!("create {}/bin: {}", dir_path.display(), e))?;

    // Derive defaults from the directory name.
    let basename = dir_path.file_name()
        .and_then(|s| s.to_str())
        .filter(|s| !s.is_empty())
        .unwrap_or("app");
    let derived_app_id = format!("com.example.{}", sanitize_id(basename));
    let app_id = app_id.unwrap_or(&derived_app_id);
    let derived_entry = format!("bin/{}", basename);
    let entry = entry.unwrap_or(&derived_entry);

    let manifest = scaffold_manifest(app_id, entry);
    write_if_absent(&dir_path.join("manifest.toml"), manifest.as_bytes())?;

    let gitignore = scaffold_gitignore();
    write_if_absent(&dir_path.join(".gitignore"), gitignore.as_bytes())?;

    println!("created Insula app skeleton in {}", dir_path.display());
    println!("  app id:    {}", app_id);
    println!("  entry:     {}", entry);
    println!();
    println!("Next steps:");
    println!("  1. Drop your binary at {}/{}", dir_path.display(), entry);
    println!("  2. insula install {} --allow-unsigned", dir_path.display());
    println!("  3. insula launch {}", app_id);
    Ok(())
}

fn write_if_absent(path: &Path, contents: &[u8]) -> Result<(), String> {
    if path.exists() {
        return Err(format!("init: refusing to overwrite {}", path.display()));
    }
    std::fs::write(path, contents)
        .map_err(|e| format!("write {}: {}", path.display(), e))
}

fn sanitize_id(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            'a'..='z' | 'A'..='Z' | '0'..='9' | '-' | '_' | '.' => out.push(c),
            ' ' | '/' | '\\' => out.push('-'),
            _ => {} // drop everything else
        }
    }
    if out.is_empty() { "app".to_string() } else { out }
}

fn scaffold_manifest(app_id: &str, entry: &str) -> String {
    format!(
        r#"# Insula manifest for {app_id}.
#
# Generated by `insula init`. See docs/spec/insula.md
# for the full schema; tweak the sections below to
# match your app's actual capability surface.

[app]
name = "{app_id}"
version = "0.1.0"
sdk-version = "1.x"

[bundle]
form = "native"
arches = ["aarch64-darwin"]
entry = "{entry}"

# Persistent storage quotas. Drop the section entirely
# if the app doesn't need to write to disk.
[storage]
data  = "10MB"
cache = "10MB"

# Outbound network. Empty hosts = no network capability
# (delete the section if you don't need any). Set
# raw-network = true for tools that need direct socket
# access (loudly disclosed at install time).
#
# [network]
# hosts = [
#   {{ name = "api.example.com", port = 443, proto = "tcp" }}
# ]

# Capabilities the user is asked to consent to at
# install time. Add keys here for sensors / DRM /
# anything not covered by the structured sections.
#
# [capabilities]
# location = false
"#
    )
}

fn scaffold_gitignore() -> &'static str {
    "# Generated by `insula init`.\n\
     /target/\n\
     /signature\n\
     /bin/*\n\
     !/bin/.gitkeep\n"
}
