[package]
name        = "tessera-tools"
version.workspace     = true
edition.workspace     = true
license.workspace     = true
repository.workspace  = true
description = "CLI tools for Tessera volumes (mkfs-tessera, tessera-debug)."
publish     = false

[[bin]]
name = "mkfs-tessera"
path = "src/bin/mkfs.rs"

[[bin]]
name = "tessera-debug"
path = "src/bin/debug.rs"

[[bin]]
name = "tessera-fsck"
path = "src/bin/fsck.rs"

[[bin]]
name = "tessera-import"
path = "src/bin/import.rs"

[[bin]]
name = "tessera-stat"
path = "src/bin/stat.rs"

[[bin]]
name = "tessera-binsplit"
path = "src/bin/binsplit.rs"

[[bin]]
name = "tessera-repack"
path = "src/bin/repack.rs"

[dependencies]
tessera-sys = { path = "../tessera-sys" }
libc        = "0.2"
sha2        = "0.10"
object      = { version = "0.36", default-features = false, features = ["read", "elf", "std"] }
iced-x86    = { version = "1.21", default-features = false, features = ["std", "decoder", "intel"] }
