//! SBPL — Sandbox Profile Language — generation.
//!
//! Apple's sandbox profile format. Each Insula app gets
//! a generated `.sb` file from its manifest at install
//! time, baked into the sandbox container at launch.
//!
//! # What this generates
//!
//! A `(version 1)` profile that:
//!
//! 1. Starts from `(deny default)` — nothing allowed by
//!    default; every capability is explicit.
//! 2. Allows the bundled binary to `process-exec` itself.
//! 3. Grants `file-read*` + `file-write*` on the
//!    container directory (the app's sandbox root,
//!    `~/Library/Containers/<bundle-id>/Data/`).
//! 4. Allows `mach-lookup` for the Aqueduct services
//!    declared in `[ipc]`.
//! 5. Allows `network-outbound` matching the `[network]`
//!    section (coarse-grained; hostname-level enforcement
//!    is the broker daemon's job per `insula.md` §4.2
//!    status caveat).
//! 6. Allows process internals (sysctl-read, mach-priv-
//!    task-port for self, signal-self) without which
//!    even trivial programs can't run.
//!
//! # What this does NOT generate
//!
//! - Entitlements XML (separate module).
//! - Hostname-level network policy (an Insula-introduced
//!   userspace broker is the layer above SBPL; SBPL just
//!   allows broker-socket access).
//! - Per-capability declarations for camera / microphone
//!   / etc.; those are TCC-mediated entitlements, not
//!   SBPL directives.

use insula_manifest::{Manifest, NetworkProto};
use std::fmt::Write;
use std::path::Path;

/// Render a manifest as an SBPL profile string.
///
/// The profile uses two parameters the caller must
/// provide at sandbox-init time via
/// `sandbox_init_with_parameters`:
///
/// - `CONTAINER_DIR` — absolute path to the app's
///   sandbox-container Data directory.
/// - `BINARY_PATH` — absolute path to the executable
///   that will be exec'd.
///
/// These are referenced in the profile via
/// `(param "CONTAINER_DIR")` etc., per Apple convention.
///
/// Equivalent to [`render_profile_with`] with no log
/// socket grant.
pub fn render_profile(manifest: &Manifest) -> String {
    render_profile_with(manifest, None)
}

/// As [`render_profile`] but optionally inserts a
/// grant for a specific unix-socket path the app needs
/// to reach (typically the `insula-logd` socket).
///
/// `(deny default)` blocks unix-socket connect, so apps
/// that want to talk to `insula-logd` need the path
/// explicitly grantd in their profile. The grant uses
/// `file-read* file-write* (literal "<path>")` — unix
/// sockets are filesystem entities on macOS, so the
/// file-* primitives apply.
pub fn render_profile_with(
    manifest: &Manifest,
    log_socket: Option<&Path>,
) -> String {
    render_profile_with_sockets(manifest, log_socket, None, None, log_socket)
}

/// As [`render_profile_with`] but supports three
/// daemon sockets (log, vestibulum, netd). Delegates
/// to [`render_profile_full`] with no praeco socket.
pub fn render_profile_with_sockets(
    manifest: &Manifest,
    log_socket: Option<&Path>,
    vestibulum_socket: Option<&Path>,
    netd_socket: Option<&Path>,
    any_socket: Option<&Path>,
) -> String {
    render_profile_full(
        manifest,
        log_socket,
        vestibulum_socket,
        netd_socket,
        None,
        None,
        any_socket,
    )
}

/// Full SBPL renderer with all five Insula daemon
/// sockets the launcher may pass through: log,
/// vestibulum, netd, praeco, tabellarius. `any_socket`
/// gates the broad `network-outbound` grant when at
/// least one is set.
pub fn render_profile_full(
    manifest: &Manifest,
    log_socket: Option<&Path>,
    vestibulum_socket: Option<&Path>,
    netd_socket: Option<&Path>,
    praeco_socket: Option<&Path>,
    tabellarius_socket: Option<&Path>,
    any_socket: Option<&Path>,
) -> String {
    let mut out = String::new();

    let _ = writeln!(out, ";; Generated by insula-host-macos");
    let _ = writeln!(
        out,
        ";; for app: {} version {}",
        manifest.app.name, manifest.app.version
    );
    let _ = writeln!(out, ";; DO NOT EDIT — regenerate from the manifest.");
    let _ = writeln!(out);
    let _ = writeln!(out, "(version 1)");
    let _ = writeln!(out, "(deny default)");
    let _ = writeln!(out);

    // Bare-minimum process internals — without these,
    // even a printf-and-exit program fails.
    let _ = writeln!(out, ";; Process internals (always required)");
    let _ = writeln!(out, "(allow process-fork)");
    let _ = writeln!(out, "(allow process-exec)");
    let _ = writeln!(out, "(allow signal (target self))");
    let _ = writeln!(out, "(allow sysctl-read)");
    let _ = writeln!(out, "(allow mach-per-user-lookup)");
    let _ = writeln!(out, "(allow ipc-posix-shm)");
    let _ = writeln!(out);

    // **Read-most-things, write-only-in-container** is
    // the App-Sandbox-shaped posture. Dyld + libc +
    // system fonts + locale data + an enormous number
    // of files outside `/usr/lib` need to be readable
    // for even printf-and-exit to work. The security
    // boundary lives on writes, not reads.
    let _ = writeln!(out, ";; File access");
    let _ = writeln!(out, "(allow file-read*)");
    let _ = writeln!(
        out,
        "(allow file* (subpath (param \"CONTAINER_DIR\")))"
    );
    let _ = writeln!(out);

    // Log-socket grant (the insula-logd unix-socket
    // path the launcher passed in).
    //
    // **v0 caveat:** `sandbox-exec` SBPL has no working
    // per-unix-socket grant form (we tested
    // `(allow network-outbound (literal ...))`,
    // `(... (path ...))`, and
    // `(... (remote unix-socket (path-literal ...)))`
    // — all deny). The pragmatic compromise: when a
    // log socket is requested, grant unrestricted
    // `network-outbound`. This is broader than ideal,
    // but it's the only thing macOS sandbox-exec
    // honors for unix-socket connect.
    //
    // The tighter posture lives behind direct
    // `sandbox_init_with_parameters` (private SPI),
    // which post-v0 work will move to. See the
    // top-of-file `launch.rs` "Future hardening" note.
    if let Some(sock) = log_socket {
        let _ = writeln!(out, ";; insula-logd socket: {}", sock.display());
        let _ = writeln!(
            out,
            "(allow file-read* file-write* (literal \"{}\"))",
            sock.display()
        );
        let _ = writeln!(out);
    }
    if let Some(sock) = vestibulum_socket {
        let _ = writeln!(out, ";; vestibulum-macos socket: {}", sock.display());
        let _ = writeln!(
            out,
            "(allow file-read* file-write* (literal \"{}\"))",
            sock.display()
        );
        let _ = writeln!(out);
    }
    if let Some(sock) = netd_socket {
        let _ = writeln!(out, ";; atrium-netd-macos socket: {}", sock.display());
        let _ = writeln!(
            out,
            "(allow file-read* file-write* (literal \"{}\"))",
            sock.display()
        );
        let _ = writeln!(out);
    }
    if let Some(sock) = praeco_socket {
        let _ = writeln!(out, ";; praeco-macos socket: {}", sock.display());
        let _ = writeln!(
            out,
            "(allow file-read* file-write* (literal \"{}\"))",
            sock.display()
        );
        let _ = writeln!(out);
    }
    if let Some(sock) = tabellarius_socket {
        let _ = writeln!(out, ";; tabellarius-macos socket: {}", sock.display());
        let _ = writeln!(
            out,
            "(allow file-read* file-write* (literal \"{}\"))",
            sock.display()
        );
        let _ = writeln!(out);
    }
    // One broad `network-outbound` grant when any of
    // the unix-domain sockets are reachable; see the
    // v0-caveat above.
    if any_socket.is_some() {
        let _ = writeln!(out, "(allow network-outbound)");
        let _ = writeln!(out);
    }

    // [ipc] services → mach-lookup whitelist.
    if let Some(ipc) = &manifest.ipc {
        if !ipc.services.is_empty() {
            let _ = writeln!(out, ";; Aqueduct services (from [ipc])");
            for svc in &ipc.services {
                // Atrium convention: each Aqueduct service exposes
                // a Mach global name "atrium.<service>".
                let _ = writeln!(
                    out,
                    "(allow mach-lookup (global-name \"atrium.{}\"))",
                    svc
                );
            }
            let _ = writeln!(out);
        }
    }

    // [network] — emit coarse network rules. Hostname
    // enforcement happens in the userspace broker layer
    // (see lib.rs / insula.md §4.2 status caveat); SBPL
    // here just allows the broker socket access + the
    // broad outbound permission the broker rides on.
    if let Some(net) = &manifest.network {
        if net.raw_network {
            let _ = writeln!(out, ";; Raw network capability");
            let _ = writeln!(out, "(allow network-outbound)");
            let _ = writeln!(out, "(allow network-inbound)");
            let _ = writeln!(out);
        } else if !net.hosts.is_empty() {
            let _ = writeln!(
                out,
                ";; Broker-mediated network ({} declared hosts)",
                net.hosts.len()
            );
            // Per-protocol coarse permission; broker
            // enforces hostname/port specifics.
            let needs_tcp = net.hosts.iter().any(|h| h.proto == NetworkProto::Tcp);
            let needs_udp = net.hosts.iter().any(|h| h.proto == NetworkProto::Udp);
            if needs_tcp {
                let _ = writeln!(
                    out,
                    "(allow network-outbound (remote tcp))"
                );
            }
            if needs_udp {
                let _ = writeln!(
                    out,
                    "(allow network-outbound (remote udp))"
                );
            }
            let _ = writeln!(out);
        }
    }

    // [render] → permit Fresco socket access. On macOS
    // there's no Fresco daemon; Pergola's macOS backend
    // talks directly to the WindowServer + Metal stack,
    // both of which need mach-lookup permissions.
    if let Some(render) = &manifest.render {
        if render.fresco {
            let _ = writeln!(out, ";; Pergola/Fresco rendering (from [render])");
            let _ = writeln!(
                out,
                "(allow mach-lookup (global-name \"com.apple.windowserver.active\"))"
            );
            let _ = writeln!(
                out,
                "(allow mach-lookup (global-name \"com.apple.cgsfp\"))"
            );
            let _ = writeln!(
                out,
                "(allow iokit-open (iokit-user-client-class \"IOAccelDevice2\"))"
            );
            let _ = writeln!(out);
        }
    }

    out
}
