//! SBPL — Sandbox Profile Language — generation.
//!
//! Apple's sandbox profile format. Each Insula app gets
//! a generated `.sb` file from its manifest at install
//! time, baked into the sandbox container at launch.
//!
//! # What this generates
//!
//! A `(version 1)` profile that:
//!
//! 1. Starts from `(deny default)` — nothing allowed by
//!    default; every capability is explicit.
//! 2. Allows the bundled binary to `process-exec` itself.
//! 3. Grants `file-read*` + `file-write*` on the
//!    container directory (the app's sandbox root,
//!    `~/Library/Containers/<bundle-id>/Data/`).
//! 4. Allows `mach-lookup` for the Aqueduct services
//!    declared in `[ipc]`.
//! 5. Allows `network-outbound` matching the `[network]`
//!    section (coarse-grained; hostname-level enforcement
//!    is the broker daemon's job per `insula.md` §4.2
//!    status caveat).
//! 6. Allows process internals (sysctl-read, mach-priv-
//!    task-port for self, signal-self) without which
//!    even trivial programs can't run.
//!
//! # What this does NOT generate
//!
//! - Entitlements XML (separate module).
//! - Hostname-level network policy (an Insula-introduced
//!   userspace broker is the layer above SBPL; SBPL just
//!   allows broker-socket access).
//! - Per-capability declarations for camera / microphone
//!   / etc.; those are TCC-mediated entitlements, not
//!   SBPL directives.

use insula_manifest::{Manifest, NetworkProto};
use std::fmt::Write;

/// Render a manifest as an SBPL profile string.
///
/// The profile uses two parameters the caller must
/// provide at sandbox-init time via
/// `sandbox_init_with_parameters`:
///
/// - `CONTAINER_DIR` — absolute path to the app's
///   sandbox-container Data directory.
/// - `BINARY_PATH` — absolute path to the executable
///   that will be exec'd.
///
/// These are referenced in the profile via
/// `(param "CONTAINER_DIR")` etc., per Apple convention.
pub fn render_profile(manifest: &Manifest) -> String {
    let mut out = String::new();

    let _ = writeln!(out, ";; Generated by insula-host-macos");
    let _ = writeln!(
        out,
        ";; for app: {} version {}",
        manifest.app.name, manifest.app.version
    );
    let _ = writeln!(out, ";; DO NOT EDIT — regenerate from the manifest.");
    let _ = writeln!(out);
    let _ = writeln!(out, "(version 1)");
    let _ = writeln!(out, "(deny default)");
    let _ = writeln!(out);

    // Bare-minimum process internals — without these,
    // even a printf-and-exit program fails.
    let _ = writeln!(out, ";; Process internals (always required)");
    let _ = writeln!(out, "(allow process-fork)");
    let _ = writeln!(out, "(allow process-exec (literal (param \"BINARY_PATH\")))");
    let _ = writeln!(out, "(allow signal (target self))");
    let _ = writeln!(out, "(allow sysctl-read)");
    let _ = writeln!(out, "(allow mach-per-user-lookup)");
    let _ = writeln!(out, "(allow ipc-posix-shm)");
    let _ = writeln!(out, "(allow file-read-metadata)");
    let _ = writeln!(out);

    // Container access (always-granted: the app's own
    // sandbox root).
    let _ = writeln!(out, ";; Container directory");
    let _ = writeln!(
        out,
        "(allow file* (subpath (param \"CONTAINER_DIR\")))"
    );
    let _ = writeln!(out);

    // System libraries and frameworks for dyld + libc.
    let _ = writeln!(out, ";; System libraries (for dyld + libc)");
    let _ = writeln!(out, "(allow file-read*");
    let _ = writeln!(out, "  (subpath \"/usr/lib\")");
    let _ = writeln!(out, "  (subpath \"/System/Library\")");
    let _ = writeln!(out, "  (subpath \"/Library/Apple\"))");
    let _ = writeln!(out);

    // [ipc] services → mach-lookup whitelist.
    if let Some(ipc) = &manifest.ipc {
        if !ipc.services.is_empty() {
            let _ = writeln!(out, ";; Aqueduct services (from [ipc])");
            for svc in &ipc.services {
                // Atrium convention: each Aqueduct service exposes
                // a Mach global name "atrium.<service>".
                let _ = writeln!(
                    out,
                    "(allow mach-lookup (global-name \"atrium.{}\"))",
                    svc
                );
            }
            let _ = writeln!(out);
        }
    }

    // [network] — emit coarse network rules. Hostname
    // enforcement happens in the userspace broker layer
    // (see lib.rs / insula.md §4.2 status caveat); SBPL
    // here just allows the broker socket access + the
    // broad outbound permission the broker rides on.
    if let Some(net) = &manifest.network {
        if net.raw_network {
            let _ = writeln!(out, ";; Raw network capability");
            let _ = writeln!(out, "(allow network-outbound)");
            let _ = writeln!(out, "(allow network-inbound)");
            let _ = writeln!(out);
        } else if !net.hosts.is_empty() {
            let _ = writeln!(
                out,
                ";; Broker-mediated network ({} declared hosts)",
                net.hosts.len()
            );
            // Per-protocol coarse permission; broker
            // enforces hostname/port specifics.
            let needs_tcp = net.hosts.iter().any(|h| h.proto == NetworkProto::Tcp);
            let needs_udp = net.hosts.iter().any(|h| h.proto == NetworkProto::Udp);
            if needs_tcp {
                let _ = writeln!(
                    out,
                    "(allow network-outbound (remote tcp))"
                );
            }
            if needs_udp {
                let _ = writeln!(
                    out,
                    "(allow network-outbound (remote udp))"
                );
            }
            let _ = writeln!(out);
        }
    }

    // [render] → permit Fresco socket access. On macOS
    // there's no Fresco daemon; Pergola's macOS backend
    // talks directly to the WindowServer + Metal stack,
    // both of which need mach-lookup permissions.
    if let Some(render) = &manifest.render {
        if render.fresco {
            let _ = writeln!(out, ";; Pergola/Fresco rendering (from [render])");
            let _ = writeln!(
                out,
                "(allow mach-lookup (global-name \"com.apple.windowserver.active\"))"
            );
            let _ = writeln!(
                out,
                "(allow mach-lookup (global-name \"com.apple.cgsfp\"))"
            );
            let _ = writeln!(
                out,
                "(allow iokit-open (iokit-user-client-class \"IOAccelDevice2\"))"
            );
            let _ = writeln!(out);
        }
    }

    out
}
